# Generated by Django 3.1.7 on 2021-03-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_attendee_course_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='note',
            field=models.FileField(null=True, upload_to='teacher/notes', verbose_name=''),
        ),
    ]
