# Generated by Django 3.1.7 on 2021-03-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='student',
        ),
    ]
